apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
    - name: redis-exporter
      port: 9121
      targetPort: 9121
