apiVersion: v1
kind: Service
metadata:
  name: lgtm
spec:
  selector:
    app: lgtm
  ports:
    - name: grafana
      port: 3000
      targetPort: 3000
    - name: loki
      port: 3100
      targetPort: 3100
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
    - name: otlp-http
      port: 4318
      targetPort: 4318
    - name: tempo
      port: 3200
      targetPort: 3200
    - name: pyroscope
      port: 4040
      targetPort: 4040
    - name: prometheus
      port: 9090
      targetPort: 9090
