spring:
  application:
    name: spring-playground

management:
  tracing:
    sampling:
      probability: 1.0  # 100% for development
  otlp:
    metrics:
      export:
        url: http://localhost:4318/v1/metrics
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/traces
    logging:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/logs

logging:
  level:
    root: info
    io.opentelemetry: DEBUG
    io.opentelemetry.exporter: DEBUG
    io.opentelemetry.exporter.otlp: DEBUG
    io.opentelemetry.sdk.logs: DEBUG
    io.opentelemetry.sdk.logs.export: DEBUG
