name: diag-k8s-label
on:
  workflow_dispatch:
jobs:
  probe-k8s:
    runs-on: [self-hosted, k8s]
    steps:
      - run: echo "k8s label routed! $RUNNER_NAME"
  probe-setname:
    if: false
    runs-on: [self-hosted, kubik-set]
    steps:
      - run: echo "scale-set-name label routed! $RUNNER_NAME"